// Package github реализует взаимодействие с GitHub API:
// публикация отчётов в PR-комментариях.
package github

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// FileReport — отчёт по одному файлу.
type FileReport struct {
	File          string   // путь к файлу
	Functions     []string // тестируемые функции
	TestsTotal    int      // всего сгенерировано тестов
	TestsPassed   int      // прошедших валидацию
	TestsPruned   int      // удалённых (failing)
	DiffCoverage  float64  // diff coverage %
	Status        string   // "success", "partial", "failed"
}

// Report — полный отчёт агента.
type Report struct {
	Files           []FileReport
	TotalGenerated  int
	TotalValidated  int
	TotalDiffCov    float64 // средний diff coverage
	Model           string  // LLM model
	Duration        time.Duration
}

// Commenter публикует отчёты в GitHub PR.
type Commenter struct {
	token   string
	owner   string
	repo    string
	prNum   int
	apiBase string
}

// NewCommenter создаёт нового комментатора.
func NewCommenter(token, owner, repo string, prNum int) *Commenter {
	return &Commenter{
		token:   token,
		owner:   owner,
		repo:    repo,
		prNum:   prNum,
		apiBase: "https://api.github.com",
	}
}

// PostReport публикует отчёт как комментарий к PR.
func (c *Commenter) PostReport(report Report) error {
	body := formatReport(report)
	return c.postComment(body)
}

// formatReport формирует Markdown-текст отчёта.
func formatReport(r Report) string {
	var sb strings.Builder

	sb.WriteString("## 🤖 Testgen Agent Report\n\n")

	if len(r.Files) > 0 {
		sb.WriteString("| File | Functions | Tests | Passed | Pruned | Diff Coverage | Status |\n")
		sb.WriteString("|------|-----------|-------|--------|--------|---------------|--------|\n")

		for _, f := range r.Files {
			funcs := strings.Join(f.Functions, ", ")
			if len(funcs) > 40 {
				funcs = funcs[:37] + "..."
			}

			statusEmoji := "✅"
			switch f.Status {
			case "partial":
				statusEmoji = "⚠️"
			case "failed":
				statusEmoji = "❌"
			}

			sb.WriteString(fmt.Sprintf("| `%s` | %s | %d | %d | %d | %.1f%% | %s |\n",
				f.File, funcs, f.TestsTotal, f.TestsPassed, f.TestsPruned, f.DiffCoverage, statusEmoji))
		}

		sb.WriteString("\n")
	}

	// Сводка
	sb.WriteString("### Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Model:** `%s`\n", r.Model))
	sb.WriteString(fmt.Sprintf("- **Files processed:** %d\n", len(r.Files)))
	sb.WriteString(fmt.Sprintf("- **Tests generated:** %d\n", r.TotalGenerated))
	sb.WriteString(fmt.Sprintf("- **Tests passed validation:** %d\n", r.TotalValidated))

	if r.TotalDiffCov > 0 {
		sb.WriteString(fmt.Sprintf("- **Average diff coverage:** %.1f%%\n", r.TotalDiffCov))
	}

	sb.WriteString(fmt.Sprintf("- **Duration:** %s\n", r.Duration.Round(time.Second)))

	if r.TotalGenerated > 0 && r.TotalValidated == 0 {
		sb.WriteString("\n> ⚠️ No tests passed validation. Consider using a more capable model or reviewing the target code.\n")
	}

	sb.WriteString("\n---\n*Generated by [testgen-agent](https://github.com/Klagvar/testgen-agent)*\n")

	return sb.String()
}

type commentRequest struct {
	Body string `json:"body"`
}

// postComment отправляет комментарий к PR через GitHub API.
func (c *Commenter) postComment(body string) error {
	url := fmt.Sprintf("%s/repos/%s/%s/issues/%d/comments", c.apiBase, c.owner, c.repo, c.prNum)

	payload, err := json.Marshal(commentRequest{Body: body})
	if err != nil {
		return fmt.Errorf("marshal comment: %w", err)
	}

	req, err := http.NewRequest("POST", url, bytes.NewReader(payload))
	if err != nil {
		return fmt.Errorf("create request: %w", err)
	}

	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("post comment: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API error %d: %s", resp.StatusCode, string(respBody))
	}

	return nil
}

// FormatReportMarkdown экспортирует formatReport для тестирования.
func FormatReportMarkdown(r Report) string {
	return formatReport(r)
}
